version: "3.9"

services:
  postgres:
    image: postgres:15.7-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - link_shortener_network
    ports:
      - "5433:5432"

  api:
    build: .
    restart: always
    depends_on:
      - postgres
    environment:
      MODULE_NAME: src.main
    volumes:
      - .:/app
    ports:
      - "0.0.0.0:8005:8005"
    networks:
      - link_shortener_network

volumes:
  pg_data:
  qdrant_data:

networks:
  link_shortener_network: