version: "3.9"

services:

  postgres:
    image: postgres:15.7-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - proacecrm_network
    ports:
      - "5432:5432"

  api:
    build: .
    restart: always
    environment:
      MODULE_NAME: src.main
    volumes:
      - .:/app
    ports:
      - "0.0.0.0:8000:8000"
    networks:
      - proacecrm_network

volumes:
  pg_data:
  qdrant_data:

networks:
  proacecrm_network:
    external: true
